name: helloGithubAction
 
on:
    push:
    schedule:
        - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: 1. pip 업그레이드
      run: python -m pip install --upgrade pip
    - name: 2. 환경 설정
      run: pip install -r requirements.txt
    - name: 3. 파이썬 실행
      run: python test.py
    - name: 4. Commit files
      run: |
        git config --local user.email "khhandrea@naver.com"
        git config --local user.name "khhandrea-auto"
        git add .
        git commit -m "ci : Run crawler and update current data"
    - name: 5. Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
