name: helloGithubAction
 
on:
    push:
    schedule:
        - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 개인 토큰을 사용할 것인지 말 것인지
        persist-credentials: false 
    - name: 1. pip 업그래이드
      run: python -m pip install --upgrade pip
    - name: 2. 환경 설정
      run: pip install -r requirements.txt
    - name: 3. 파이썬 실행
      run: python test.py
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
      with:
        author_name: khhandrea[bot]
        message: 'ci: Run crawler and update current data'
